branch-defaults:
  master:
    environment: WiseguyUserApi-production
  qa:
    environment: WiseguyUserApi-qa
deploy:
  artifact: package.zip
environment-defaults:
  WiseguyUserApi-production:
    branch: null
    repository: null
  WiseguyUserApi-qa:
    branch: null
    repository: null
global:
  application_name: wiseguy-user-api
  default_ec2_keyname: null
  default_platform: Node.js 12 running on 64bit Amazon Linux 2
  default_region: eu-west-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: git
  workspace_type: Application
